# Generated by Django 4.1 on 2022-08-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='creator',
        ),
    ]
